-- ==========================================
-- 1. SCHEMAS (Module Organization)
-- ==========================================

-- History Logs
CREATE SCHEMA IF NOT EXISTS audit;
-- Users, Roles, Permissions
CREATE SCHEMA IF NOT EXISTS identity;
-- Settings, Feature Flags
CREATE SCHEMA IF NOT EXISTS system;
-- Units, Citations
CREATE SCHEMA IF NOT EXISTS shared;
-- Recipes, Ingredients, Tags
CREATE SCHEMA IF NOT EXISTS app_kitchen;

-- ==========================================
-- 2. AUDIT LOGGING (The "Black Box")
-- ==========================================

-- The Central Log Table
CREATE TABLE audit.logs
(
    id          integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    schema_name text        NOT NULL,
    table_name  text        NOT NULL,
    record_id   jsonb       NOT NULL, -- Flexible ID storage
    operation   text        NOT NULL, -- 'INSERT', 'UPDATE', 'DELETE'
    old_data    jsonb,
    new_data    jsonb,
    changed_by  uuid,                 -- Set via "SET LOCAL app.current_user_id = '...'"
    changed_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE audit.logs IS 'Centralized audit log table. Only used for tables that does not have their own dedicated shadow table.';
COMMENT ON COLUMN audit.logs.record_id IS 'Flexible ID storage. Can be a UUID, an integer, a slug, or a JSON object representing a composite key.';

CREATE INDEX idx_audit_record ON audit.logs (table_name, record_id);
CREATE INDEX idx_audit_record_id ON audit.logs USING GIN (record_id);
CREATE INDEX idx_audit_time ON audit.logs (changed_at);

-- The Generic Trigger Function
CREATE OR REPLACE FUNCTION audit.log_change() RETURNS TRIGGER AS
$$
DECLARE
    current_user_id UUID;

    -- Variables for dynamic key extraction
    key_col         TEXT;
    key_object      JSONB := '{}'::jsonb; -- Start with an empty object
    row_data        JSONB; -- Holds either NEW or OLD data
    i               INTEGER;
BEGIN
    -- 1. Get User ID
    BEGIN
        current_user_id := current_setting('app.current_user_id')::UUID;
    EXCEPTION
        WHEN OTHERS THEN
            current_user_id := NULL;
    END;

    -- 2. Determine which row data to use for ID extraction
    -- For DELETE, we must use OLD. For INSERT/UPDATE, we use NEW.
    IF (TG_OP = 'DELETE') THEN
        row_data := to_jsonb(OLD);
    ELSE
        row_data := to_jsonb(NEW);
    END IF;

    -- 3. Build the Composite Key ID
    -- If no arguments are provided, default to 'id'
    IF TG_NARGS = 0 THEN
        key_object := jsonb_build_object('id', row_data ->> 'id');
    ELSE
        -- Loop through all arguments (column names) passed to the trigger
        FOR i IN 0 .. (TG_NARGS - 1)
            LOOP
                key_col := TG_ARGV[i];
                -- Add { "col_name": "value" } to our key object
                key_object := key_object || jsonb_build_object(key_col, row_data ->> key_col);
            END LOOP;
    END IF;

    -- 4. Insert the Log
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO audit.logs (schema_name, table_name, record_id, operation, old_data, changed_by)
        VALUES (TG_TABLE_SCHEMA, TG_TABLE_NAME, key_object, 'DELETE', to_jsonb(OLD), current_user_id);
        RETURN OLD;

    ELSIF (TG_OP = 'UPDATE') THEN
        IF (OLD IS NOT DISTINCT FROM NEW) THEN RETURN NEW; END IF;

        INSERT INTO audit.logs (schema_name, table_name, record_id, operation, old_data, new_data, changed_by)
        VALUES (TG_TABLE_SCHEMA, TG_TABLE_NAME, key_object, 'UPDATE', to_jsonb(OLD), to_jsonb(NEW), current_user_id);
        RETURN NEW;

    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO audit.logs (schema_name, table_name, record_id, operation, new_data, changed_by)
        VALUES (TG_TABLE_SCHEMA, TG_TABLE_NAME, key_object, 'INSERT', to_jsonb(NEW), current_user_id);
        RETURN NEW;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- 3. IDENTITY SCHEMA (User and Role Management)
-- ==========================================

--- IDENTITY.USERS ---

CREATE TABLE identity.users
(
    id            uuid PRIMARY KEY, -- Generated v7 in Axum
    username      text        NOT NULL,
    email         text        NOT NULL,
    password_hash text        NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE identity.users IS 'Global user registry for the entire Super-App.';
COMMENT ON COLUMN identity.users.id IS 'UUID v7 generated by the application for time-sortable indexing.';

CREATE TRIGGER audit_identity_users
    AFTER UPDATE
    ON identity.users
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change();

--- IDENTITY.ROLES ---

CREATE TABLE identity.roles
(
    id   text PRIMARY KEY,    -- e.g. "admin", "editor"
    name text NOT NULL UNIQUE -- e.g. "Administrator"
);

COMMENT ON TABLE identity.roles IS 'Roles are used to group permissions together. A user can have multiple roles.';
COMMENT ON COLUMN identity.roles.id IS 'Unique identifier (e.g., "admin"). Used in code.';

CREATE TRIGGER audit_identity_roles
    AFTER UPDATE
    ON identity.roles
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change();

--- IDENTITY.USERS_ROLES ---

-- Users can have multiple roles
CREATE TABLE identity.user_roles
(
    user_id uuid REFERENCES identity.users (id),
    role_id text REFERENCES identity.roles (id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TRIGGER audit_identity_user_roles
    AFTER UPDATE
    ON identity.user_roles
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('user_id', 'role_id');

--- IDENTITY.PERMISSIONS ---

CREATE TABLE identity.permissions
(
    slug        text PRIMARY KEY, -- e.g. "kitchen.recipe.create"
    description text              -- Optional: "Allows creating new recipes"
);

COMMENT ON TABLE identity.permissions IS 'Permissions are used to define what actions a user can perform. Any value in this table must also have a hard-coded representation in code.';
COMMENT ON COLUMN identity.permissions.slug IS 'Unique identifier (e.g., "users:read"). Used in code.';

CREATE TRIGGER audit_identity_permissions
    AFTER UPDATE
    ON identity.permissions
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('slug');

--- IDENTITY.ROLE_PERMISSIONS ---

CREATE TABLE identity.role_permissions
(
    role_id         text NOT NULL REFERENCES identity.roles (id) ON DELETE CASCADE,
    permission_slug text NOT NULL REFERENCES identity.permissions (slug) ON DELETE CASCADE, -- e.g. "users:read"
    PRIMARY KEY (role_id, permission_slug)
);

CREATE TRIGGER audit_identity_role_permissions
    AFTER UPDATE
    ON identity.role_permissions
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('role_id', 'permission_slug');

-- ==========================================
-- 4. SYSTEM SCHEMA (Settings and Feature Flags)
-- ==========================================

--- SYSTEM.SETTINGS ---

CREATE TABLE system.settings
(
    slug          TEXT PRIMARY KEY,                   -- Technical ID: "maintenance_mode"

    -- The Value (Universal)
    value         JSONB NOT NULL,                     -- true, 50, "My App"

    -- The UI Metadata (For the Dashboard)
    type          TEXT  NOT NULL,                     -- "boolean", "integer", "string", "select"
    setting_group TEXT           DEFAULT 'general',   -- "security", "uploads", "legal"

    -- Localized UI Text
    label         JSONB NOT NULL DEFAULT '{}'::jsonb, -- {"en": "Maintenance Mode", "sv": "Underhållsläge"}
    description   JSONB NOT NULL DEFAULT '{}'::jsonb, -- {"en": "Disables access...", "sv": "Stänger av..."}

    -- Audit
    updated_at    TIMESTAMPTZ    DEFAULT NOW(),
    updated_by    UUID REFERENCES identity.users (id)
);

COMMENT ON TABLE system.settings IS 'Global system configuration. Cached in RAM. UI text is localized.';
COMMENT ON COLUMN system.settings.slug IS 'Unique identifier (e.g., "default_currency"). Used in code.';

CREATE TRIGGER audit_system_settings
    AFTER UPDATE
    ON system.settings
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('slug');

--- SYSTEM.FEATURE_FLAGS ---

CREATE TABLE system.feature_flags
(
    id          uuid PRIMARY KEY default gen_random_uuid(),

    slug        TEXT UNIQUE NOT NULL,           -- Technical ID: "new_search_v2"
    is_enabled  BOOLEAN          DEFAULT FALSE, -- Master Switch

    -- Logic Engine (Who gets this feature?)
    -- { "type": "percentage", "value": 20 }
    -- { "type": "allow_list", "ids": [...] }
    rules       JSONB            DEFAULT '{
      "type": "global"
    }'::jsonb,

    -- Internal Docs (Usually not localized as it's for devs, but consistent with your app)
    description JSONB            DEFAULT '{}'::jsonb,

    created_at  TIMESTAMPTZ      DEFAULT NOW(),
    updated_at  TIMESTAMPTZ      DEFAULT NOW()
);

COMMENT ON TABLE system.feature_flags IS 'Feature flags that can be enabled/disabled globally.';
COMMENT ON COLUMN system.feature_flags.slug IS 'Unique identifier (e.g., "new_dashboard_v2"). Used in code.';

CREATE TRIGGER audit_system_feature_flags
    AFTER UPDATE
    ON system.feature_flags
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('id');

-- ==========================================
-- 5. SHARED SCHEMA (Shared Infrastructure)
-- ==========================================

--- SHARED.UNITS ---

CREATE TABLE shared.units
(
    slug           text PRIMARY KEY,
    name           jsonb   NOT NULL DEFAULT '{}'::jsonb,
    type           text    NOT NULL,
    system         text,
    base_unit_slug text REFERENCES shared.units (slug),
    factor         numeric NOT NULL,
    "offset"       numeric          DEFAULT 0,
    created_at     timestamptz      DEFAULT now()
);

COMMENT ON TABLE shared.units IS 'Universal physical units (Mass, Volume, Time, Temp).';
COMMENT ON COLUMN shared.units.slug IS 'Unique identifier (e.g., "kg", "cup_us"). Used in code.';
COMMENT ON COLUMN shared.units.name IS 'Localized names (e.g., {"en": "Cup", "sv": "Kopp"}).';
COMMENT ON COLUMN shared.units.base_unit_slug IS 'If set, this unit converts TO this base. If NULL, this IS the base.';
COMMENT ON COLUMN shared.units.factor IS 'Multiplier to reach the base unit (e.g., kg -> g is 1000.0).';

CREATE TRIGGER audit_shared_units
    AFTER UPDATE
    ON shared.units
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('slug');

--- SHARED.DATA_SOURCES ---

CREATE TABLE shared.data_sources
(
    id           UUID PRIMARY KEY,
    name         TEXT NOT NULL,
    url          TEXT,
    retrieved_at DATE DEFAULT CURRENT_DATE,
    version      TEXT
);

COMMENT ON TABLE shared.data_sources IS 'Registry of external data authorities (USDA, OpenFoodFacts).';

CREATE TRIGGER audit_shared_data_sources
    AFTER UPDATE
    ON shared.data_sources
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('id');

CREATE TABLE shared.nutrients
(
    id           UUID PRIMARY KEY,
    name         TEXT NOT NULL,
    unit_slug    TEXT REFERENCES shared.units (slug),
    standard_dri NUMERIC,
    is_macro     BOOLEAN DEFAULT FALSE
);

COMMENT ON TABLE shared.nutrients IS 'Nutrients (e.g., Protein, Carbohydrate, Fiber) and their standard reference.';
COMMENT ON COLUMN shared.nutrients.unit_slug IS 'The unit in which the nutrient is measured.';
COMMENT ON COLUMN shared.nutrients.standard_dri IS 'The standard reference for the nutrient (e.g., 100g), according to an 80kg male person.';
COMMENT ON COLUMN shared.nutrients.is_macro IS 'Whether the nutrient is considered a "macro" nutrient (e.g., Fiber).';

CREATE TRIGGER audit_shared_nutrients
    AFTER UPDATE
    ON shared.nutrients
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('id');

-- ==========================================
-- 6. KITCHEN SCHEMA (Domain Logic)
-- ==========================================

--- APP_KITCHEN.TAGS ---

CREATE TABLE app_kitchen.tags
(
    id       UUID PRIMARY KEY,
    slug     TEXT UNIQUE NOT NULL,
    name     JSONB       NOT NULL DEFAULT '{}'::jsonb,
    category TEXT                 DEFAULT 'general'
);

COMMENT ON TABLE app_kitchen.tags IS 'Domain-specific descriptors (Vegan, Dinner, Spicy).';

CREATE TRIGGER audit_app_kitchen_tags
    AFTER UPDATE
    ON app_kitchen.tags
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('id');

--- APP_KITCHEN.RECIPES ---

CREATE TABLE app_kitchen.cuisines
(
    id        UUID PRIMARY KEY,
    parent_id UUID REFERENCES app_kitchen.cuisines (id),
    name      JSONB NOT NULL UNIQUE
);

COMMENT ON TABLE app_kitchen.cuisines IS 'Hierarchical cultural origins (Italian -> Emilian).';

CREATE TRIGGER audit_app_kitchen_cuisines
    AFTER UPDATE
    ON app_kitchen.cuisines
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('id');

--- APP_KITCHEN.CULINARY_ITEMS ---

CREATE TABLE app_kitchen.culinary_items
(
    id          UUID PRIMARY KEY,
    name        JSONB NOT NULL,
    description JSONB
);

COMMENT ON TABLE app_kitchen.culinary_items IS 'The abstract concept of a dish (e.g., "Spaghetti Bolognese") distinct from a specific recipe.';

CREATE TRIGGER audit_app_kitchen_culinary_items
    AFTER UPDATE
    ON app_kitchen.culinary_items
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('id');

--- APP_KITCHEN.INGREDIENTS ---

CREATE TABLE app_kitchen.ingredients
(
    id             UUID PRIMARY KEY,
    parent_id      UUID REFERENCES app_kitchen.ingredients (id),
    verified_by    UUID REFERENCES identity.users (id),

    name           JSONB NOT NULL DEFAULT '{}'::jsonb,
    description    JSONB,
    density_g_ml   NUMERIC,
    piece_weight_g NUMERIC,
    properties     JSONB          DEFAULT '{}'::jsonb,

    created_at     TIMESTAMPTZ    DEFAULT NOW(),
    updated_at     TIMESTAMPTZ    DEFAULT NOW()
);

COMMENT ON TABLE app_kitchen.ingredients IS 'The central database of food items.';
COMMENT ON COLUMN app_kitchen.ingredients.parent_id IS 'Hierarchy for variants (Potato -> French Fries).';
COMMENT ON COLUMN app_kitchen.ingredients.density_g_ml IS 'Critical for converting Volume (cup) to Mass (g).';
COMMENT ON COLUMN app_kitchen.ingredients.properties IS 'Sparse data (ABV, Scoville, Smoke Point) stored as JSONB.';

Create TRIGGER audit_app_kitchen_ingredients
    AFTER UPDATE
    ON app_kitchen.ingredients
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('id');

--- APP_KITCHEN.INGREDIENT_CONVERSIONS ---

CREATE TABLE app_kitchen.ingredient_conversions
(
    id             UUID PRIMARY KEY,
    ingredient_id  UUID REFERENCES app_kitchen.ingredients (id) ON DELETE CASCADE,
    unit_slug      TEXT REFERENCES shared.units (slug),
    grams_per_unit NUMERIC NOT NULL,
    source_id      UUID REFERENCES shared.data_sources (id)
);

COMMENT ON TABLE app_kitchen.ingredient_conversions IS 'Links abstract units (clove, pinch) to physical mass for specific ingredients.';

CREATE TRIGGER audit_app_kitchen_ingredient_conversions
    AFTER UPDATE
    ON app_kitchen.ingredient_conversions
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('id');

--- APP_KITCHEN.INGREDIENT_PROPOSALS ---

CREATE TABLE app_kitchen.ingredient_proposals
(
    id            UUID PRIMARY KEY,
    ingredient_id UUID REFERENCES app_kitchen.ingredients (id) ON DELETE CASCADE,
    user_id       UUID    REFERENCES identity.users (id) ON DELETE SET NULL,
    property      TEXT    NOT NULL,
    value         NUMERIC NOT NULL,
    status        TEXT    DEFAULT 'pending',
    upvotes       INTEGER DEFAULT 0,
    downvotes     INTEGER DEFAULT 0
);

COMMENT ON TABLE app_kitchen.ingredient_proposals IS 'Staging area for user-submitted data before verification.';

CREATE TRIGGER audit_app_kitchen_ingredient_proposals
    AFTER UPDATE
    ON app_kitchen.ingredient_proposals
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('id');

--- APP_KITCHEN.INGREDIENT_NUTRIENTS ---

CREATE TABLE app_kitchen.ingredient_nutrients
(
    ingredient_id UUID REFERENCES app_kitchen.ingredients (id) ON DELETE CASCADE,
    nutrient_id   UUID REFERENCES shared.nutrients (id),
    amount        NUMERIC NOT NULL, -- Per 100g/ml
    PRIMARY KEY (ingredient_id, nutrient_id)
);

COMMENT ON TABLE app_kitchen.ingredient_nutrients IS 'Links ingredients to nutrients (e.g., Protein, Carbohydrate, Fiber).';
COMMENT ON COLUMN app_kitchen.ingredient_nutrients.amount IS 'The amount of the nutrient per 100g/ml.';

CREATE TRIGGER audit_app_kitchen_ingredient_nutrients
    AFTER UPDATE
    ON app_kitchen.ingredient_nutrients
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('ingredient_id', 'nutrient_id');

--- APP_KITCHEN.RECIPES ---

CREATE TABLE app_kitchen.recipes
(
    id                   UUID PRIMARY KEY,
    culinary_item_id     UUID REFERENCES app_kitchen.culinary_items (id),
    user_id              UUID REFERENCES identity.users (id),

    name                 TEXT    NOT NULL,
    description          TEXT,
    original_lang        TEXT        DEFAULT 'en',

    cuisine_id           UUID REFERENCES app_kitchen.cuisines (id),
    style                TEXT,

    yield_quantity       NUMERIC NOT NULL,
    yield_unit           TEXT    NOT NULL,

    prep_time_seconds    INTEGER,
    active_time_seconds  INTEGER,
    passive_time_seconds INTEGER,

    created_at           TIMESTAMPTZ DEFAULT NOW(),
    updated_at           TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE app_kitchen.recipes IS 'Specific user execution of a dish.';
COMMENT ON COLUMN app_kitchen.recipes.style IS 'Authenticity marker (traditional, fusion, quick).';
COMMENT ON COLUMN app_kitchen.recipes.active_time_seconds IS 'Actual work time (chopping, stirring).';
COMMENT ON COLUMN app_kitchen.recipes.passive_time_seconds IS 'Waiting time (baking, marinating).';

CREATE TRIGGER audit_app_kitchen_recipes
    AFTER UPDATE
    ON app_kitchen.recipes
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('id');

--- APP_KITCHEN.RECIPE_INGREDIENTS ---

CREATE TABLE app_kitchen.recipe_ingredients
(
    id                   UUID PRIMARY KEY,
    recipe_id            UUID REFERENCES app_kitchen.recipes (id) ON DELETE CASCADE,

    ingredient_id        UUID REFERENCES app_kitchen.ingredients (id),
    sub_recipe_id        UUID REFERENCES app_kitchen.recipes (id),

    choice_group_id      UUID,
    choice_index         INTEGER DEFAULT 0,

    declared_quantity    NUMERIC NOT NULL,
    declared_unit_slug   TEXT REFERENCES shared.units (slug),

    normalized_quantity  NUMERIC,
    normalized_unit_slug TEXT REFERENCES shared.units (slug),

    note                 TEXT,
    is_optional          BOOLEAN DEFAULT FALSE,
    is_garnish           BOOLEAN DEFAULT FALSE,

    CONSTRAINT check_item_source CHECK (
        (ingredient_id IS NOT NULL AND sub_recipe_id IS NULL) OR
        (ingredient_id IS NULL AND sub_recipe_id IS NOT NULL)
        )
);

COMMENT ON TABLE app_kitchen.recipe_ingredients IS 'Links recipes to ingredients OR sub-recipes (Exclusive Arc).';
COMMENT ON COLUMN app_kitchen.recipe_ingredients.sub_recipe_id IS 'Recursive link (e.g., adding "Pesto Sauce" recipe to "Pasta" recipe).';
COMMENT ON COLUMN app_kitchen.recipe_ingredients.choice_group_id IS 'UUID linking alternatives (e.g., Sugar vs Honey).';
COMMENT ON COLUMN app_kitchen.recipe_ingredients.declared_quantity IS 'The exact amount the author wrote.';
COMMENT ON COLUMN app_kitchen.recipe_ingredients.normalized_quantity IS 'The system-calculated standard amount (usually in base units).';

CREATE TRIGGER audit_app_kitchen_recipe_ingredients
    AFTER UPDATE
    ON app_kitchen.recipe_ingredients
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('id');

--- APP_KITCHEN.RECIPE_NOTES ---

CREATE TABLE app_kitchen.recipe_notes
(
    id                     UUID PRIMARY KEY,
    recipe_id              UUID REFERENCES app_kitchen.recipes (id) ON DELETE CASCADE,
    linked_choice_group_id UUID,
    linked_choice_index    INTEGER,
    body                   TEXT NOT NULL
);

COMMENT ON TABLE app_kitchen.recipe_notes IS 'Contextual instructions triggered by specific ingredient choices.';

CREATE TRIGGER audit_app_kitchen_recipe_notes
    AFTER UPDATE
    ON app_kitchen.recipe_notes
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('id');


--- APP_KITCHEN.RECIPE_TAGS ---

CREATE TABLE app_kitchen.recipe_tags
(
    recipe_id UUID REFERENCES app_kitchen.recipes (id) ON DELETE CASCADE,
    tag_id    UUID REFERENCES app_kitchen.tags (id) ON DELETE CASCADE,
    user_id   UUID REFERENCES identity.users (id),
    PRIMARY KEY (recipe_id, tag_id, user_id)
);

COMMENT ON TABLE app_kitchen.recipe_tags IS 'Polymorphic join table for tagging recipes. Includes user ID for voting logic.';

CREATE TRIGGER audit_app_kitchen_recipe_tags
    AFTER UPDATE
    ON app_kitchen.recipe_tags
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('recipe_id', 'tag_id', 'user_id');

--- APP_KITCHEN.CULINARY_ITEM_TAGS ---

CREATE TABLE app_kitchen.culinary_item_tags
(
    item_id UUID REFERENCES app_kitchen.culinary_items (id) ON DELETE CASCADE,
    tag_id  UUID REFERENCES app_kitchen.tags (id) ON DELETE CASCADE,
    user_id UUID REFERENCES identity.users (id),
    PRIMARY KEY (item_id, tag_id, user_id)
);

COMMENT ON TABLE app_kitchen.culinary_item_tags IS 'Tags for abstract culinary items.';

CREATE TRIGGER audit_app_kitchen_culinary_item_tags
    AFTER UPDATE
    ON app_kitchen.culinary_item_tags
    FOR EACH ROW
EXECUTE FUNCTION audit.log_change('item_id', 'tag_id', 'user_id');
