-- =============================
-- SCHEMAS (Module Organization)
-- =============================

-- Users, Roles, Permissions
CREATE SCHEMA IF NOT EXISTS identity;
-- Settings, Feature Flags
CREATE SCHEMA IF NOT EXISTS system;
-- Units, Citations
CREATE SCHEMA IF NOT EXISTS shared;
-- Recipes, Ingredients, Tags
CREATE SCHEMA IF NOT EXISTS app_kitchen;

-- ==========================================
-- IDENTITY SCHEMA (User and Role Management)
-- ==========================================

--- ACCOUNTS.USERS ---

CREATE TABLE accounts.users
(
    id            uuid PRIMARY KEY, -- Generated v7 in Axum
    username      text        NOT NULL,
    email         text        NOT NULL,
    password_hash text        NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE accounts.users IS 'Global user registry for the entire Super-App.';
COMMENT ON COLUMN accounts.users.id IS 'UUID v7 generated by the application for time-sortable indexing.';

--- ACCOUNTS.ROLES ---

CREATE TABLE accounts.roles
(
    id   text PRIMARY KEY,    -- e.g. "admin", "editor"
    name text NOT NULL UNIQUE -- e.g. "Administrator"
);

COMMENT ON TABLE accounts.roles IS 'Roles are used to group permissions together. A user can have multiple roles.';
COMMENT ON COLUMN accounts.roles.id IS 'Unique identifier (e.g., "admin"). Used in code.';

--- ACCOUNTS.USERS_ROLES ---

CREATE TABLE accounts.user_roles
(
    user_id uuid REFERENCES accounts.users (id),
    role_id text REFERENCES accounts.roles (id),
    PRIMARY KEY (user_id, role_id)
);

--- ACCOUNTS.PERMISSIONS ---

CREATE TABLE accounts.permissions
(
    slug        text PRIMARY KEY, -- e.g. "kitchen.recipe.create"
    description text              -- Optional: "Allows creating new recipes"
);

COMMENT ON TABLE accounts.permissions IS 'Permissions are used to define what actions a user can perform. Any value in this table must also have a hard-coded representation in code.';
COMMENT ON COLUMN accounts.permissions.slug IS 'Unique identifier (e.g., "users:read"). Used in code.';

--- ACCOUNTS.ROLE_PERMISSIONS ---

CREATE TABLE accounts.role_permissions
(
    role_id         text NOT NULL REFERENCES accounts.roles (id) ON DELETE CASCADE,
    permission_slug text NOT NULL REFERENCES accounts.permissions (slug) ON DELETE CASCADE, -- e.g. "users:read"
    PRIMARY KEY (role_id, permission_slug)
);

-- ==========================================
-- SYSTEM SCHEMA (Settings and Feature Flags)
-- ==========================================

--- SYSTEM.SETTINGS ---

CREATE TABLE system.settings
(
    slug          TEXT PRIMARY KEY,                   -- Technical ID: "maintenance_mode"

    -- The Value (Universal)
    value         JSONB NOT NULL,                     -- true, 50, "My App"

    -- The UI Metadata (For the Dashboard)
    type          TEXT  NOT NULL,                     -- "boolean", "integer", "string", "select"
    setting_group TEXT           DEFAULT 'general',   -- "security", "uploads", "legal"

    -- Localized UI Text
    label         JSONB NOT NULL DEFAULT '{}'::jsonb, -- {"en": "Maintenance Mode", "sv": "Underhållsläge"}
    description   JSONB NOT NULL DEFAULT '{}'::jsonb, -- {"en": "Disables access...", "sv": "Stänger av..."}

    -- Audit
    updated_at    TIMESTAMPTZ    DEFAULT NOW(),
    updated_by    UUID REFERENCES accounts.users (id)
);

COMMENT ON TABLE system.settings IS 'Global system configuration. Cached in RAM. UI text is localized.';
COMMENT ON COLUMN system.settings.slug IS 'Unique identifier (e.g., "default_currency"). Used in code.';

--- SYSTEM.FEATURE_FLAGS ---

CREATE TABLE system.feature_flags
(
    id          uuid PRIMARY KEY default gen_random_uuid(),

    slug        TEXT UNIQUE NOT NULL,           -- Technical ID: "new_search_v2"
    is_enabled  BOOLEAN          DEFAULT FALSE, -- Master Switch

    -- Logic Engine (Who gets this feature?)
    -- { "type": "percentage", "value": 20 }
    -- { "type": "allow_list", "ids": [...] }
    rules       JSONB            DEFAULT '{
      "type": "global"
    }'::jsonb,

    -- Internal Docs (Usually not localized as it's for devs, but consistent with your app)
    description JSONB            DEFAULT '{}'::jsonb,

    created_at  TIMESTAMPTZ      DEFAULT NOW(),
    updated_at  TIMESTAMPTZ      DEFAULT NOW()
);

COMMENT ON TABLE system.feature_flags IS 'Feature flags that can be enabled/disabled globally.';
COMMENT ON COLUMN system.feature_flags.slug IS 'Unique identifier (e.g., "new_dashboard_v2"). Used in code.';

-- ==========================================
-- 5. SHARED SCHEMA (Shared Infrastructure)
-- ==========================================

--- SHARED.UNITS ---

CREATE TABLE shared.units
(
    slug           text PRIMARY KEY,
    name           jsonb   NOT NULL DEFAULT '{}'::jsonb,
    type           text    NOT NULL,
    system         text,
    base_unit_slug text REFERENCES shared.units (slug),
    factor         numeric NOT NULL,
    "offset"       numeric          DEFAULT 0,
    created_at     timestamptz      DEFAULT now()
);

COMMENT ON TABLE shared.units IS 'Universal physical units (Mass, Volume, Time, Temp).';
COMMENT ON COLUMN shared.units.slug IS 'Unique identifier (e.g., "kg", "cup_us"). Used in code.';
COMMENT ON COLUMN shared.units.name IS 'Localized names (e.g., {"en": "Cup", "sv": "Kopp"}).';
COMMENT ON COLUMN shared.units.base_unit_slug IS 'If set, this unit converts TO this base. If NULL, this IS the base.';
COMMENT ON COLUMN shared.units.factor IS 'Multiplier to reach the base unit (e.g., kg -> g is 1000.0).';

--- SHARED.DATA_SOURCES ---

CREATE TABLE shared.data_sources
(
    id           UUID PRIMARY KEY,
    name         TEXT NOT NULL,
    url          TEXT,
    retrieved_at DATE DEFAULT CURRENT_DATE,
    version      TEXT
);

COMMENT ON TABLE shared.data_sources IS 'Registry of external data authorities (USDA, OpenFoodFacts).';


-- SHARED.NUTRIENTS ---

CREATE TABLE shared.nutrients
(
    id           UUID PRIMARY KEY,
    name         TEXT NOT NULL,
    unit_slug    TEXT REFERENCES shared.units (slug),
    standard_dri NUMERIC,
    is_macro     BOOLEAN DEFAULT FALSE
);

COMMENT ON TABLE shared.nutrients IS 'Nutrients (e.g., Protein, Carbohydrate, Fiber) and their standard reference.';
COMMENT ON COLUMN shared.nutrients.unit_slug IS 'The unit in which the nutrient is measured.';
COMMENT ON COLUMN shared.nutrients.standard_dri IS 'The standard reference for the nutrient (e.g., 100g), according to an 80kg male person.';
COMMENT ON COLUMN shared.nutrients.is_macro IS 'Whether the nutrient is considered a "macro" nutrient (e.g., Fiber).';

-- =============================
-- KITCHEN SCHEMA (Domain Logic)
-- =============================

--- APP_KITCHEN.TAGS ---

CREATE TABLE app_kitchen.tags
(
    id       UUID PRIMARY KEY,
    slug     TEXT UNIQUE NOT NULL,
    name     JSONB       NOT NULL DEFAULT '{}'::jsonb,
    category TEXT                 DEFAULT 'general'
);

COMMENT ON TABLE app_kitchen.tags IS 'Domain-specific descriptors (Vegan, Dinner, Spicy).';

--- APP_KITCHEN.RECIPES ---

CREATE TABLE app_kitchen.cuisines
(
    id        UUID PRIMARY KEY,
    parent_id UUID REFERENCES app_kitchen.cuisines (id),
    name      JSONB NOT NULL UNIQUE
);

COMMENT ON TABLE app_kitchen.cuisines IS 'Hierarchical cultural origins (Italian -> Emilian).';

--- APP_KITCHEN.CULINARY_ITEMS ---

CREATE TABLE app_kitchen.culinary_items
(
    id          UUID PRIMARY KEY,
    name        JSONB NOT NULL,
    description JSONB
);

COMMENT ON TABLE app_kitchen.culinary_items IS 'The abstract concept of a dish (e.g., "Spaghetti Bolognese") distinct from a specific recipe.';

--- APP_KITCHEN.INGREDIENTS ---

CREATE TABLE app_kitchen.ingredients
(
    id             UUID PRIMARY KEY,
    parent_id      UUID REFERENCES app_kitchen.ingredients (id),
    verified_by    UUID REFERENCES accounts.users (id),

    name           JSONB NOT NULL DEFAULT '{}'::jsonb,
    description    JSONB,
    density_g_ml   NUMERIC,
    piece_weight_g NUMERIC,
    properties     JSONB          DEFAULT '{}'::jsonb,

    created_at     TIMESTAMPTZ    DEFAULT NOW(),
    updated_at     TIMESTAMPTZ    DEFAULT NOW()
);

COMMENT ON TABLE app_kitchen.ingredients IS 'The central database of food items.';
COMMENT ON COLUMN app_kitchen.ingredients.parent_id IS 'Hierarchy for variants (Potato -> French Fries).';
COMMENT ON COLUMN app_kitchen.ingredients.density_g_ml IS 'Critical for converting Volume (cup) to Mass (g).';
COMMENT ON COLUMN app_kitchen.ingredients.properties IS 'Sparse data (ABV, Scoville, Smoke Point) stored as JSONB.';

--- APP_KITCHEN.INGREDIENT_CONVERSIONS ---

CREATE TABLE app_kitchen.ingredient_conversions
(
    id             UUID PRIMARY KEY,
    ingredient_id  UUID REFERENCES app_kitchen.ingredients (id) ON DELETE CASCADE,
    unit_slug      TEXT REFERENCES shared.units (slug),
    grams_per_unit NUMERIC NOT NULL,
    source_id      UUID REFERENCES shared.data_sources (id)
);

COMMENT ON TABLE app_kitchen.ingredient_conversions IS 'Links abstract units (clove, pinch) to physical mass for specific ingredients.';

--- APP_KITCHEN.INGREDIENT_PROPOSALS ---

CREATE TABLE app_kitchen.ingredient_proposals
(
    id            UUID PRIMARY KEY,
    ingredient_id UUID REFERENCES app_kitchen.ingredients (id) ON DELETE CASCADE,
    user_id       UUID    REFERENCES accounts.users (id) ON DELETE SET NULL,
    property      TEXT    NOT NULL,
    value         NUMERIC NOT NULL,
    status        TEXT    DEFAULT 'pending',
    upvotes       INTEGER DEFAULT 0,
    downvotes     INTEGER DEFAULT 0
);

COMMENT ON TABLE app_kitchen.ingredient_proposals IS 'Staging area for user-submitted data before verification.';

--- APP_KITCHEN.INGREDIENT_NUTRIENTS ---

CREATE TABLE app_kitchen.ingredient_nutrients
(
    ingredient_id UUID REFERENCES app_kitchen.ingredients (id) ON DELETE CASCADE,
    nutrient_id   UUID REFERENCES shared.nutrients (id),
    amount        NUMERIC NOT NULL, -- Per 100g/ml
    PRIMARY KEY (ingredient_id, nutrient_id)
);

COMMENT ON TABLE app_kitchen.ingredient_nutrients IS 'Links ingredients to nutrients (e.g., Protein, Carbohydrate, Fiber).';
COMMENT ON COLUMN app_kitchen.ingredient_nutrients.amount IS 'The amount of the nutrient per 100g/ml.';

--- APP_KITCHEN.RECIPES ---

CREATE TABLE app_kitchen.recipes
(
    id                   UUID PRIMARY KEY,
    culinary_item_id     UUID REFERENCES app_kitchen.culinary_items (id),
    user_id              UUID REFERENCES accounts.users (id),

    name                 TEXT    NOT NULL,
    description          TEXT,
    original_lang        TEXT        DEFAULT 'en',

    cuisine_id           UUID REFERENCES app_kitchen.cuisines (id),
    style                TEXT,

    yield_quantity       NUMERIC NOT NULL,
    yield_unit           TEXT    NOT NULL,

    prep_time_seconds    INTEGER,
    active_time_seconds  INTEGER,
    passive_time_seconds INTEGER,

    created_at           TIMESTAMPTZ DEFAULT NOW(),
    updated_at           TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE app_kitchen.recipes IS 'Specific user execution of a dish.';
COMMENT ON COLUMN app_kitchen.recipes.style IS 'Authenticity marker (traditional, fusion, quick).';
COMMENT ON COLUMN app_kitchen.recipes.active_time_seconds IS 'Actual work time (chopping, stirring).';
COMMENT ON COLUMN app_kitchen.recipes.passive_time_seconds IS 'Waiting time (baking, marinating).';

--- APP_KITCHEN.RECIPE_INGREDIENTS ---

CREATE TABLE app_kitchen.recipe_ingredients
(
    id                   UUID PRIMARY KEY,
    recipe_id            UUID REFERENCES app_kitchen.recipes (id) ON DELETE CASCADE,

    ingredient_id        UUID REFERENCES app_kitchen.ingredients (id),
    sub_recipe_id        UUID REFERENCES app_kitchen.recipes (id),

    choice_group_id      UUID,
    choice_index         INTEGER DEFAULT 0,

    declared_quantity    NUMERIC NOT NULL,
    declared_unit_slug   TEXT REFERENCES shared.units (slug),

    normalized_quantity  NUMERIC,
    normalized_unit_slug TEXT REFERENCES shared.units (slug),

    note                 TEXT,
    is_optional          BOOLEAN DEFAULT FALSE,
    is_garnish           BOOLEAN DEFAULT FALSE,

    CONSTRAINT check_item_source CHECK (
        (ingredient_id IS NOT NULL AND sub_recipe_id IS NULL) OR
        (ingredient_id IS NULL AND sub_recipe_id IS NOT NULL)
        )
);

COMMENT ON TABLE app_kitchen.recipe_ingredients IS 'Links recipes to ingredients OR sub-recipes (Exclusive Arc).';
COMMENT ON COLUMN app_kitchen.recipe_ingredients.sub_recipe_id IS 'Recursive link (e.g., adding "Pesto Sauce" recipe to "Pasta" recipe).';
COMMENT ON COLUMN app_kitchen.recipe_ingredients.choice_group_id IS 'UUID linking alternatives (e.g., Sugar vs Honey).';
COMMENT ON COLUMN app_kitchen.recipe_ingredients.declared_quantity IS 'The exact amount the author wrote.';
COMMENT ON COLUMN app_kitchen.recipe_ingredients.normalized_quantity IS 'The system-calculated standard amount (usually in base units).';

--- APP_KITCHEN.RECIPE_NOTES ---

CREATE TABLE app_kitchen.recipe_notes
(
    id                     UUID PRIMARY KEY,
    recipe_id              UUID REFERENCES app_kitchen.recipes (id) ON DELETE CASCADE,
    linked_choice_group_id UUID,
    linked_choice_index    INTEGER,
    body                   TEXT NOT NULL
);

COMMENT ON TABLE app_kitchen.recipe_notes IS 'Contextual instructions triggered by specific ingredient choices.';

--- APP_KITCHEN.RECIPE_TAGS ---

CREATE TABLE app_kitchen.recipe_tags
(
    recipe_id UUID REFERENCES app_kitchen.recipes (id) ON DELETE CASCADE,
    tag_id    UUID REFERENCES app_kitchen.tags (id) ON DELETE CASCADE,
    user_id   UUID REFERENCES accounts.users (id),
    PRIMARY KEY (recipe_id, tag_id, user_id)
);

COMMENT ON TABLE app_kitchen.recipe_tags IS 'Polymorphic join table for tagging recipes. Includes user ID for voting logic.';

--- APP_KITCHEN.CULINARY_ITEM_TAGS ---

CREATE TABLE app_kitchen.culinary_item_tags
(
    item_id UUID REFERENCES app_kitchen.culinary_items (id) ON DELETE CASCADE,
    tag_id  UUID REFERENCES app_kitchen.tags (id) ON DELETE CASCADE,
    user_id UUID REFERENCES accounts.users (id),
    PRIMARY KEY (item_id, tag_id, user_id)
);

COMMENT ON TABLE app_kitchen.culinary_item_tags IS 'Tags for abstract culinary items.';

-- ===============================
-- AUDIT LOGGING (The "Black Box")
-- ===============================

-- Enable the extension (Requires Postgres to be started with shared_preload_libraries='pgaudit')
CREATE EXTENSION IF NOT EXISTS pgaudit;

-- Create a dedicated role purely for flagging tables for auditing.
DO $$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'audit_flag_role') THEN
            CREATE ROLE audit_flag_role;
        END IF;
    END
$$;

-- Run this at the end of your migration for every schema you want audited
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA identity TO audit_flag_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA system TO audit_flag_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA shared TO audit_flag_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app_kitchen TO audit_flag_role;
